### ISSUE TITLE
data not updating?

### ISSUE THREAD

**Issue by king6cong** [rust-lang-nursery/thanks#78] opened 2017-03-06 07:07 UTC
https://thanks.rust-lang.org/rust/all-time

It seems the data has not been updated for quite some time.

**Comment by steveklabnik** [comment] 2017-03-06 17:58
Yes, this is a duplicate of https://github.com/rust-lang-nursery/thanks/issues/13

I am hoping to fix this this week, or next week at the absolute latest. Thanks!

**Closed by steveklabnik** 2017-03-06 17:58 UTC
